export const GOOGLE_FONTS = [
    "Roboto",
    "Open Sans",
    "Space Grotesk",
    "Lato",
    "Montserrat",
    "Oswald",
    "Raleway",
    "Merriweather",
    "Poppins",
    "Playfair Display",
    "Ubuntu",
    "Dancing Script",
    "Great Vibes",
    "Pacifico",
    "Satisfy",
    "Bebas Neue",
    "Lobster",
    "Abril Fatface",
    "Comfortaa",
    "Righteous",
    "Cinzel",
    "Inter",
    "Nunito",
    "Work Sans",
    "Fira Sans",
    "Quicksand",
    "Barlow",
    "Inconsolata",
    "Josefin Sans",
    "Libre Baskerville",
    "Anton",
    "Assistant",
    "Hind Siliguri",
    "Cabin",
    "Bitter",
    "Oxygen",
    "Dosis",
    "Arvo",
    "Varela Round",
    "Crimson Text",
    "Cairo",
    "Exo 2",
    "Kanit",
    "Acme",
    "Architects Daughter",
    "Bree Serif",
    "Courgette",
    "Crete Round",
    "Gloria Hallelujah",
    "Indie Flower",
    "Kaushan Script",
    "Permanent Marker",
    "Shadows Into Light",
    "Tangerine",
    "Yellowtail",
    "Zeyada"
];
